version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fintech_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_local
      MYSQL_DATABASE: fintech_wallet
      MYSQL_USER: yhonattan_dev
      MYSQL_PASSWORD: dev_password_123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: